title:  <p align="center"> Uri Katz </p>
logo:   <a href="url"><img src="/images/profilepic.png?raw=true" height="auto" width="200" style="border-radius:50%"></a>
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/urika">LinkedIn</a> |
  <a href="https://github.com/katzurik">GitHub</a>
  </p>

  <p align="justify">
  I am a M.Sc Statistics student in Tel Aviv univesity and Data Scientist @ Aquant 
  </p>

theme: jekyll-theme-minimal


