theme: jekyll-theme-minimal
title: [Uri katz]
logo: [https://github.com/katzurik/katzurik.github.io/blob/main/images/profilepic.png?raw=true]
#description: [A short description of your site's purpose]
description: [M.Sc Statistics student in Tel Aviv univesity]
linkedin: [urika]

  avatar: https://github.com/katzurik/katzurik.github.io/blob/main/images/profilepic.png


