title:  <p align="center"> Uri Katz </p>
logo:   "/images/bio_circle.png?raw=true"
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/urika">LinkedIn</a> |
  <a href="https://github.com/katzurik">GitHub</a>
  </p>

  <p align="justify">
  I am a M.Sc Statistics student at Tel Aviv university and a Data Scientist @ Aquant
  </p>

theme: jekyll-theme-minimal


