title:  <p align="center"> Uri Katz </p>
logo:  "/images/profilepic.png?raw=true"
#description: [A short description of your site's purpose]
description: [M.Sc Statistics student in Tel Aviv univesity]
linkedin: [urika]
theme: jekyll-theme-minimal


